export const BAND_NAMES_256 = [
  'Eternal Core','Nickel Forge','Iron Heartbeat','Primordial Mantle','Lithic Roar','Subduction Song','Magma Heart','Rift Whisper','Volcanic Pulse','Crustal Thunder','Tectonic Echo','Seismic Lullaby','Planetary Forge','Core Resonance','Mantle Dream','Abyssal Maw','Hadal Thunder','Trench Oracle','Benthic Choir','Pressure Veil','Deep Mantle Song','Geothermal Hum','Iron Core Pulse','Nickel Veil','Primordial Roar','Subterranean Whisper','Lithosphere Pulse','Mantle Chamber','Core Song','Planetary Heart','Eternal Forge','Deepest Resonance',
  'Mariana Pulse','Hadal Depths','Oceanic Spine','Continental Rumble','Mountain Root','Ancient Soil','Seabed Choir','Trench Echo','Pelagic Dream','Abyssal Current','Hydrothermal Song','Pressure Chamber','Oceanic Veil','Tectonic Drift','Rift Valley Hum','Submarine Thunder','Coral Heart','Deep Current Pulse','Ocean Floor Forge','Benthic Resonance','Mariana Whisper','Hadal Lullaby','Pelagic Roar','Continental Song','Seabed Pulse','Trench Heart','Abyssal Forge','Oceanic Dream','Pressure Song','Deep Sea Resonance','Hydrothermal Veil','Mariana Core',
  'Forest Floor','Canopy Breath','Jungle Canopy','Savanna Heart','River Stone','Earth Breath','Gaia Hum','Biosphere Song','Thunder Root','Storm Cradle','Wind Weaver','Cloud Chamber','Dawn Chorus','Human Veil','Vocal Ridge','Breath Chamber','Presence Spark','Clarity Thread','Life Resonance','Soil Symphony','Root Network','Leaf Whisper','Pollen Pulse','Mycelial Song','Rainforest Hum','Savanna Pulse','River Echo','Earth Song','Gaia Pulse','Biosphere Veil','Life Thread','Organic Resonance',
  'Vocal Spark','Throat Chamber','Chest Resonance','Nasal Veil','Presence Ridge','Clarity Peak','Sibilant Edge','Bite Burst','Air Shelf','Breath Spark','Voice Thread','Human Hum','Emotional Core','Soul Whisper','Heartbeat Echo','Vocal Forge','Presence Veil','Clarity Song','Sibilance Dream','Air Resonance','Breath Pulse','Voice Lullaby','Human Spark','Emotional Veil','Soul Pulse','Heart Song','Vocal Dream','Presence Core','Clarity Forge','Sibilant Whisper','Air Heart','Breath Resonance',
  'Tropospheric Dance','Cloud Weaver','Storm Pulse','Rain Veil','Lightning Thread','Wind Ridge','Fog Chamber','Mist Spark','Dawn Veil','Dusk Echo','Twilight Hum','Atmosphere Song','Weather Pulse','Cumulus Heart','Stratus Whisper','Nimbus Resonance','Thunder Song','Lightning Dream','Raindrop Pulse','Wind Forge','Cloud Veil','Mist Thread','Fog Resonance','Dawn Spark','Dusk Lullaby','Twilight Pulse','Atmosphere Veil','Weather Song','Cumulus Echo','Stratus Dream','Nimbus Heart','Thunder Veil',
  'Lightning Veil','Aurora Thread','Ion Whisper','Magnetosphere Ring','Solar Wind Hymn','Helios Harp','Van Allen Veil','Orbital Echo','Lunar Reflection','Meteor Shimmer','Exospheric Spark','Satellite Choir','Stratospheric Veil','Ionospheric Dance','Aurora Pulse','Magneto Song','Solar Veil','Helios Dream','Van Allen Pulse','Orbital Whisper','Lunar Heart','Meteor Forge','Exospheric Hum','Satellite Resonance','Stratospheric Song','Ionospheric Spark','Aurora Lullaby','Magneto Veil','Solar Pulse','Helios Resonance','Van Allen Dream','Orbital Song',
  'Lunar Reflection','Mars Dust','Jovian Thunder','Saturn Ring Song','Venus Veil','Mercury Pulse','Neptune Whisper','Uranus Dream','Pluto Edge','Asteroid Shimmer','Comet Trail','Solar Flare Heart','Coronal Song','Heliosphere Veil','Interplanetary Hum','Moonlit Resonance','Jupiter Pulse','Saturn Echo','Venus Spark','Mercury Forge','Neptune Lullaby','Uranus Veil','Pluto Song','Asteroid Dream','Comet Pulse','Solar Flare Whisper','Coronal Resonance','Heliosphere Song','Interplanetary Veil','Moonlit Pulse','Jovian Dream','Saturn Heart',
  'Stellar Drift','Nebula Heart','Galactic Pulse','Cosmic Root','Quasar Whisper','Black Hole Lullaby','Dark Matter Song','Cosmic Microwave','Quantum Foam','Void Resonance','Star Forge','Nebula Veil','Galactic Edge','Observable Dream','Universal Hum','Eternity’s Resonance','Photon Veil','Neutrino Song','Graviton Pulse','Singularity Heart','Big Bang Echo','Multiverse Whisper','Cosmic Horizon','Dark Energy Dream','Stellar Nursery','Supernova Spark','Pulsar Choir','Quasar Forge','Black Hole Veil','Cosmic Infinity','Observable Edge','Eternal Resonance',
];

if (BAND_NAMES_256.length !== 256) {
  throw new Error(`BAND_NAMES_256 must contain exactly 256 names; got ${BAND_NAMES_256.length}.`);
}
